### PR TITLE
fix: BREAKING CHANGE: use per imap action timout instead of global plling ti…

### PR DESCRIPTION
**Pull request by lucidNTR**
…meout,

exponential backup strategy for failure,
exclude successful individual mails from frailed pollings,
recover better for failure to update checkpoint document

@lucychambers @jo @gr2m 
needs merge of download-email-attachments PR before

### CODE REVIEW

**Comment by gr2m** [comment]
If it’s a breaking change, you have to use `BREAKING CHANGE:` in the commit body (3rd line or later)

**Comment by tlvince** [comment]
Depends on https://github.com/eHealthAfrica/download-email-attachments/pull/7.

**Comment by lucidNTR** [comment]
sorry youre right its force push fixed

**Comment by tlvince** [comment]
There needs to be a blank line before `BREAKING CHANGE`. (Sry).

**Comment by lucidNTR** [comment]
fixed commit message and changes for new download email attachments commits

**Comment by lucidNTR** [comment]
@tlvince @jo @lucychambers

**Comment by tlvince** [comment]
:+1:

**Pull request merged**
