### PR TITLE
tests & coverage

### PR DESCRIPTION
**Pull request by gr2m**
closes https://github.com/eHealthAfrica/kazana-email-box/issues/6
part of https://github.com/eHealthAfrica/kazana/issues/131

### CODE REVIEW

**Comment by gr2m** [comment]
ping @jo – once that’s merged, we have test coverage setup in all kazana repos

**Comment by jo** [comment]
Looks good to me but I'd like @lucidNTR to have a look at it.

**Comment by gr2m** [comment]
good call :th

**Comment by lucidNTR** [comment]
thanks :-)

**Pull request merged**
